[package]
name = "sley-grep"
version.workspace = true
description = "Shared regex and grep matching engine for sley."
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
sley-core = { path = "../sley-core", version = "0.3.0" }

[lints]
workspace = true
