[package]
name = "git-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "git_cli"
path = "src/lib.rs"

[[bin]]
name = "git-rs"
path = "src/main.rs"

[dependencies]
git-archive = { path = "../git-archive" }
git-core = { path = "../git-core" }
git-diff-merge = { path = "../git-diff-merge" }
git-fetch = { path = "../git-fetch" }
git-formats = { path = "../git-formats" }
git-fsck = { path = "../git-fsck" }
git-odb = { path = "../git-odb" }
git-pack = { path = "../git-pack" }
git-refs = { path = "../git-refs" }
git-rev = { path = "../git-rev" }
git-sequencer = { path = "../git-sequencer" }
git-testkit = { path = "../git-testkit" }
git-transport = { path = "../git-transport", features = ["http-client"] }
git-worktree = { path = "../git-worktree" }

[lints]
workspace = true
