[package]
name = "sley-submodule"
description = "Submodule operations for sley."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sley-core.workspace = true
sley-diff-merge.workspace = true
sley-config.workspace = true
sley-object.workspace = true
sley-odb.workspace = true
sley-rev.workspace = true

[lints]
workspace = true
