[package]
name = "sley-config"
version.workspace = true
description = "Native-Rust implementation of Git's configuration system: parsing, serialization, typed values, and include resolution."
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
sley-core = { path = "../sley-core", version = "0.1.0" }

[lints]
workspace = true
