[package]
name = "git-odb"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }
git-core = { path = "../git-core" }
git-formats = { path = "../git-formats" }
git-object = { path = "../git-object" }
git-pack = { path = "../git-pack" }

[lints]
workspace = true
