[package]
name = "git-sequencer"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
git-core = { path = "../git-core" }
git-formats = { path = "../git-formats" }
git-object = { path = "../git-object" }
git-odb = { path = "../git-odb" }
git-refs = { path = "../git-refs" }
git-worktree = { path = "../git-worktree" }

[lints]
workspace = true
