[package]
name = "git-remote"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
git-config = { path = "../git-config" }
git-core = { path = "../git-core" }
git-fetch = { path = "../git-fetch" }
git-odb = { path = "../git-odb" }
git-pack = { path = "../git-pack" }
git-protocol = { path = "../git-protocol" }
git-refs = { path = "../git-refs" }
git-rev = { path = "../git-rev" }
git-transport = { path = "../git-transport" }
git-worktree = { path = "../git-worktree" }

[lints]
workspace = true
