[package]
name = "sley-fsck"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
sley-core = { path = "../sley-core" }
sley-formats = { path = "../sley-formats" }
sley-object = { path = "../sley-object" }
sley-odb = { path = "../sley-odb" }

[lints]
workspace = true
