[package]
name = "sley-strbuf-expand"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Git strbuf_expand-style format-string expansion for sley."

[dependencies]
sley-core = { path = "../sley-core", version = "0.3.0" }

[lints]
workspace = true
